[package]
name = "inlarn"
version = "0.1.0"
edition = "2021"
author = "isaachhk02 {Isaac Ordoñez Fornós} 2024"

[dependencies]
widestring = "0.5"
windows-registry = "0.1.2"
netuser-rs = "0.1"
windows = { version = "0.34", features = ["Win32_Security", "Win32_Foundation"] }